class Constants:
  
  MODALITY_TYPES = set(['atac', 'rna'])
  DEFAULT_DIST = dict([
      ('atac', 'IndependentBernoulliWrapper'),
      ('rna', 'IndependentZeroInflatedNegativeBinomialWrapper')
  ])
  CONFIG_FIELD_IO = 'io'
  CONFIG_FIELD_IO_DATADIR = 'datadir'
  CONFIG_FIELD_MODALITY = 'modalities'
  CONFIG_FIELD_MODALITY_TYPE = 'type'
  CONFIG_FIELD_MODALITY_ORDER = 'order'
  CONFIG_FIELD_MODALITY_DIST = 'dist'
  CONFIG_FIELD_MODALITY_N_LAYERS = 'n_layers'
  CONFIG_FIELD_MODALITY_N_CLUSTERS = 'n_clusters'
  CONFIG_FIELD_MODALITY_N_LATENT_DIMS = 'n_latent_dims'
  CONFIG_FIELD_MODALITY_PREPROCESS = 'preprocess'
  CONFIG_FIELD_MODALITY_PREPROCESS_BINARIZE = 'binarize'
  CONFIG_FIELD_MODALITY_PREPROCESS_FILTER_OBS = 'filter_cells'
  CONFIG_FIELD_MODALITY_PREPROCESS_FILTER_VAR = 'filter_genes'
  CONFIG_FIELD_MODALITY_PREPROCESS_NORMLIBSIZE = 'norm_libsize'
  CONFIG_FIELD_MODALITY_PREPROCESS_QC = 'control_vars'
  CONFIG_FIELD_MODALITY_REQUIRED = [
      CONFIG_FIELD_MODALITY_TYPE
  ]
  CONFIG_FIELD_SAMPLE = 'samples'
  CONFIG_FIELD_SAMPLE_MODALITY = 'modalities'
  CONFIG_FIELD_SAMPLE_MODALITY_MTX = 'matrix'
  CONFIG_FIELD_SAMPLE_MODALITY_OBS = 'barcodes'
  CONFIG_FIELD_SAMPLE_MODALITY_VAR = 'features'
  CONFIG_FIELD_SAMPLE_MODALITY_OBS_COLNAMES = 'barcodes_colnames'
  CONFIG_FIELD_SAMPLE_MODALITY_VAR_COLNAMES = 'features_colnames'
  CONFIG_FIELD_SAMPLE_MODALITY_REQUIRED = [
    CONFIG_FIELD_SAMPLE_MODALITY_MTX,
    CONFIG_FIELD_SAMPLE_MODALITY_OBS,
    CONFIG_FIELD_SAMPLE_MODALITY_VAR,
    CONFIG_FIELD_SAMPLE_MODALITY_OBS_COLNAMES,
    CONFIG_FIELD_SAMPLE_MODALITY_VAR_COLNAMES
  ]
  PREPROCESS_STEP_MAPPING = dict([
      (CONFIG_FIELD_MODALITY_PREPROCESS_BINARIZE, 'Binarize'),
      (CONFIG_FIELD_MODALITY_PREPROCESS_FILTER_OBS, 'FilterCells'),
      (CONFIG_FIELD_MODALITY_PREPROCESS_FILTER_VAR, 'FilterGenes'),
      (CONFIG_FIELD_MODALITY_PREPROCESS_NORMLIBSIZE, 'NormalizeLibrarySize'),
      (CONFIG_FIELD_MODALITY_PREPROCESS_QC, 'FilterQC')
  ])