class Constants:

  TENSOR_NAME_X = 'matrix'
  TENSOR_NAME_ORIGIONAL_X = '_matrix'
  TENSOR_NAME_LIBSIZE = 'libsize'
  TENSOR_NAME_BATCH = 'batch_effect'

  TENSORFLOW_NAME_REGEX = r'^[A-Za-z0-9.][A-Za-z0-9_.\\/>-]*$'
  TENSORFLOW_NAME_START_REGEX = r'^[A-Za-z0-9.]'

  SUPPORTED_MODALITY_TYPES = set(['atac', 'rna'])
  DEFAULT_MODALITY_DISTRIBUTION = dict([
      ('atac', 'IndependentBernoulli'),
      ('rna', 'IndependentZeroInflatedNegativeBinomial')
  ])

  CONFIG_FIELD_IO = 'io'
  CONFIG_FIELD_IO_DATADIR = 'datadir'

  CONFIG_FIELD_MODALITY = 'modalities'
  CONFIG_FIELD_MODALITY_TYPE = 'type'
  CONFIG_FIELD_MODALITY_DIST = 'dist'
  CONFIG_FIELD_MODALITY_FILTER = 'filters'

  CONFIG_FIELD_MODALITY_REQUIRED = [
      CONFIG_FIELD_MODALITY_TYPE
  ]

  CONFIG_FIELD_SAMPLE = 'samples'
  CONFIG_FIELD_SAMPLE_DESCRIPTION = 'description'
  CONFIG_FIELD_SAMPLE_REQUIRED = [
    CONFIG_FIELD_MODALITY
  ]
  CONFIG_FIELD_SAMPLE_MODALITY_MTX = 'matrix'
  CONFIG_FIELD_SAMPLE_MODALITY_OBS = 'barcodes'
  CONFIG_FIELD_SAMPLE_MODALITY_VAR = 'features'
  CONFIG_FIELD_SAMPLE_MODALITY_OBS_COLNAMES = 'barcodes_colnames'
  CONFIG_FIELD_SAMPLE_MODALITY_VAR_COLNAMES = 'features_colnames'
  CONFIG_FIELD_SAMPLE_MODALITY_LIBSIZE_COLNAME = 'libsize_colname'
  CONFIG_FIELD_SAMPLE_MODALITY_BATCH_COLNAMES = 'batch_colnames'
  CONFIG_FIELD_SAMPLE_MODALITY_HAS_HEADERS = 'has_headers'
  CONFIG_FIELD_SAMPLE_MODALITY_REQUIRED = [
    CONFIG_FIELD_SAMPLE_MODALITY_MTX,
    CONFIG_FIELD_SAMPLE_MODALITY_OBS,
    CONFIG_FIELD_SAMPLE_MODALITY_VAR,
  ]

  CONFIG_FIELD_MODEL = 'model'
  CONFIG_FIELD_MODEL_TRAINING = 'training'
  CONFIG_FIELD_MODEL_TRAINING_OPTIMIZER = 'optimizer'
  CONFIG_FIELD_MODEL_TRAINING_N_EPOCHS = 'max_n_epochs'
  CONFIG_FIELD_MODEL_TRAINING_LEARNING_RATE = 'max_n_epochs'
  CONFIG_FIELD_MODEL_DATASET = 'dataset'
  CONFIG_FIELD_MODEL_DATASET_BATCHSIZE = 'batch_size'
  CONFIG_FIELD_MODEL_COMPONENT = 'components'
  CONFIG_FIELD_MODEL_REQUIRED = [
    CONFIG_FIELD_MODEL_COMPONENT
  ]
  CONFIG_FIELD_COMPONENT_MODALITY_NAMES = 'modality_names'
  CONFIG_FIELD_COMPONENT_MODALITY_DIST_NAMES = 'distribution_names'
  CONFIG_FIELD_COMPONENT_CONDITION = 'conditioned_on'
  CONFIG_FIELD_COMPONENT_N_LATENT_DIMS = 'n_latent_dims'
  CONFIG_FIELD_COMPONENT_N_PRIORS = 'n_priors'
  CONFIG_FIELD_COMPONENT_N_ENCODER_LAYERS = 'n_encoder_layers'
  CONFIG_FIELD_COMPONENT_N_DECODER_LAYERS = 'n_decoder_layers'
  CONFIG_FIELD_COMPONENT_N_PROGRESSIVE_EPOCHS = 'n_progressive_epochs'
  CONFIG_FIELD_COMPONENT_REQUIRED = [
    CONFIG_FIELD_MODALITY
  ]
  CONFIG_FIELD_COMPONENT_MODALITIES_REQUIRED = [
    'name'
  ]